In [8]:
import matplotlib.pyplot as plt

import numpy as np

import torch

In [5]:
results = torch.load('../final_results.pt')

In [29]:
print(results['layer_0_perf']['exec-time-approx'])
print(results['layer_0_perf']['exec-time-compute'])

[0, 4.511207342147827, 9.61325690150261, 14.669755473732948, 18.799742683768272]
[153.89589592814445, 146.99972420930862, 146.7863917350769, 147.23029546439648, 0.1719687134027481]


In [31]:
NUM_SCHEMES = 5

timing = np.zeros((NUM_SCHEMES, NUM_SCHEMES, 2))
for i in range(NUM_SCHEMES):
    base_approx = results['layer_0_perf']['exec-time-approx'][i]
    base_compute = results['layer_0_perf']['exec-time-compute'][i]
    for j in range(NUM_SCHEMES):
        timing[i,:,0] = np.array(results[i]['layer_1_perf']['exec-time-approx']) + base_approx
        timing[i,:,1] = np.array(results[i]['layer_1_perf']['exec-time-compute']) + base_compute
        print(i, j, timing[i,j,:])
        
print(timing)

0 0 [  0.         154.18691561]
0 1 [  0.96488185 154.16880138]
0 2 [  1.87994726 154.15087901]
0 3 [  2.74707936 154.16686051]
0 4 [  3.45439836 154.05088291]
1 0 [  4.51120734 147.23625407]
1 1 [  5.43887354 147.27789164]
1 2 [  6.22540899 147.37014659]
1 3 [  7.14943372 147.22279459]
1 4 [  8.08319449 147.1837759 ]
2 0 [  9.6132569  147.02741057]
2 1 [ 10.65515727 147.05656655]
2 2 [ 11.5723107  147.10353129]
2 3 [ 12.33052462 147.09766582]
2 4 [ 13.59442063 147.04607241]
3 0 [ 14.66975547 147.54736796]
3 1 [ 15.67145437 147.49070443]
3 2 [ 16.45185798 147.55358547]
3 3 [ 17.42007211 147.60700241]
3 4 [ 18.10757257 147.37658761]
4 0 [18.79974268  0.42179599]
4 1 [19.73817497  0.47759153]
4 2 [20.59230767  0.50430186]
4 3 [21.3526953   0.52086636]
4 4 [22.33834565  0.32072887]
[[[  0.         154.18691561]
  [  0.96488185 154.16880138]
  [  1.87994726 154.15087901]
  [  2.74707936 154.16686051]
  [  3.45439836 154.05088291]]

 [[  4.51120734 147.23625407]
  [  5.43887354 147.27789164

In [38]:
print(results[4]['layer_1_perf']['exec-time-approx'])
print(results[4]['layer_1_perf']['exec-time-compute'])

[0, 0.9384322911500931, 1.7925649881362915, 2.552952617406845, 3.538602963089943]
[0.2498272806406021, 0.30562281608581543, 0.33233314752578735, 0.34889765083789825, 0.14876015484333038]


In [36]:
accs = np.zeros((NUM_SCHEMES, NUM_SCHEMES))
for i in range(NUM_SCHEMES):
    for j in range(NUM_SCHEMES):
        accs[i,j] = results[i][j]['acc']
        print(i, j, accs[i,j])

0 0 97.39583587646484
0 1 95.48611450195312
0 2 93.92361450195312
0 3 92.01388549804688
0 4 93.22916412353516
1 0 97.39583587646484
1 1 95.48611450195312
1 2 93.92361450195312
1 3 92.01388549804688
1 4 93.22916412353516
2 0 97.39583587646484
2 1 95.48611450195312
2 2 93.92361450195312
2 3 91.84027862548828
2 4 93.22916412353516
3 0 97.39583587646484
3 1 95.48611450195312
3 2 93.92361450195312
3 3 92.01388549804688
3 4 93.22916412353516
4 0 97.39583587646484
4 1 95.48611450195312
4 2 93.92361450195312
4 3 92.01388549804688
4 4 93.22916412353516


array([[97.39583588, 95.4861145 , 93.9236145 , 92.0138855 , 93.22916412],
       [97.39583588, 95.4861145 , 93.9236145 , 92.0138855 , 93.22916412],
       [97.39583588, 95.4861145 , 93.9236145 , 91.84027863, 93.22916412],
       [97.39583588, 95.4861145 , 93.9236145 , 92.0138855 , 93.22916412],
       [97.39583588, 95.4861145 , 93.9236145 , 92.0138855 , 93.22916412]])